name: pull-build-test

on:
  pull_request_target:
    types: [labeled]
      
env:
  ANDROID_FIREBASE_JSON: ${{secrets.ANDROID_FIREBASE_JSON}}
  SERVER_ADDRESS: ${{secrets.SERVER_ADDRESS}}
  GMAIL_USERNAME: ${{secrets.GMAIL_USERNAME}}
  GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}

jobs:
  flutter-build:
    name: Run flutter build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe-for-build')
    defaults:
      run:
        working-directory: aptiche
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Decode Google Services JSON
        run: |
          touch android/app/google-services.json
          echo $ANDROID_FIREBASE_JSON >> android/app/google-services.json
          cat android/app/google-services.json
      - name: Flutter Build
        run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: $SERVER_ADDRESS
          server_port: 465
          username: $GMAIL_USERNAME
          password: $GMAIL_PASSWORD
          subject: APTICHE App PR Build
          to: aptiche@googlegroups.com
          from: $GMAIL_USERNAME
          body: PR Build success on ${{github.repository}}
          attachments: build/app/outputs/flutter-apk/app-release.apk
